spring.application.name=pottery-workshops
spring.datasource.url=jdbc:postgresql://localhost:5432/pottery-workshops
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# H2 console configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console